# services
services:
  # guacamole
  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PASSWORD: '5dqgLX0SyP6695YEmzE63CeMNaPBpsTn'
      POSTGRESQL_USER: guacamole_user
      WEBAPP_CONTEXT: ROOT
    image: guacamole/guacamole
    ports:
    - 8080:8080/tcp # Guacamole is on /.
    restart: always

  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
    
  # postgres
  postgres:
    container_name: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: '5dqgLX0SyP6695YEmzE63CeMNaPBpsTn'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z